Build

diff --git a/templates/services/init.j2 b/templates/services/init.j2
--- a/templates/services/init.j2
+++ b/templates/services/init.j2
@@ -1,14 +1,14 @@
 #! /bin/sh
 #
-# skeleton  example file to build /etc/init.d/ scripts.
-#       This file should be used to construct scripts for /etc/init.d.
+# skeleton	example file to build /etc/init.d/ scripts.
+#		This file should be used to construct scripts for /etc/init.d.
 #
-#       Written by Miquel van Smoorenburg <miquels@cistron.nl>.
-#       Modified for Debian
-#       by Ian Murdock <imurdock@gnu.ai.mit.edu>.
+#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
+#		Modified for Debian
+#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
 #               Further changes by Javier Fernandez-Sanguino <jfs@debian.org>
 #
-# Version:  @(#)skeleton  1.9  26-Feb-2001  miquels@cistron.nl
+# Version:	@(#)skeleton  1.9  26-Feb-2001  miquels@cistron.nl
 #
 ### BEGIN INIT INFO
 # Provides:          supervisor
@@ -24,7 +24,7 @@
 . /lib/lsb/init-functions
 
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
-DAEMON=/usr/local/bin/supervisord
+DAEMON=/usr/bin/supervisord
 NAME=supervisord
 DESC=supervisor
 
@@ -38,7 +38,7 @@ DODTIME=5                   # Time to wait for the server to die, in seconds
 
 # Include supervisor defaults if available
 if [ -f /etc/default/supervisor ] ; then
-    . /etc/default/supervisor
+	. /etc/default/supervisor
 fi
 DAEMON_OPTS="-c {{ elao_supervisor_config_file }} $DAEMON_OPTS"
 
@@ -79,7 +79,7 @@ force_stop() {
             kill -9 $pid
             [ -n "$DODTIME" ] && sleep "$DODTIME"s
             if running ; then
-                echo "Cannot kill $DESC (pid=$pid)!"
+                echo "Cannot kill $NAME (pid=$pid)!"
                 exit 1
             fi
         fi
@@ -90,56 +90,77 @@ force_stop() {
 
 case "$1" in
   start)
-    if [ -e $PIDFILE ]; then
-        echo "$DESC already running with pid: `cat $PIDFILE`"
-        exit 0
-    fi
-    echo -n "Starting $DESC: "
-    start-stop-daemon --start --quiet --pidfile $PIDFILE \
-        --exec $DAEMON -- $DAEMON_OPTS
-    test -f $PIDFILE || sleep 1
+	echo -n "Starting $DESC: "
+	start-stop-daemon --start --quiet --pidfile $PIDFILE \
+		--startas $DAEMON -- $DAEMON_OPTS
+	test -f $PIDFILE || sleep 1
         if running ; then
             echo "$NAME."
         else
             echo " ERROR."
         fi
-    ;;
+	;;
   stop)
-    echo -n "Stopping $DESC: "
-    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE 
-    echo "$NAME."
-    ;;
+	echo -n "Stopping $DESC: "
+	start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE 
+	echo "$NAME."
+	;;
   force-stop)
-    echo -n "Forcefully stopping $DESC: "
-    force_stop
-    if ! running ; then
-        echo "$NAME."
-    else
-        echo " ERROR."
-    fi
-    ;;
+	echo -n "Forcefully stopping $DESC: "
+        force_stop
+        if ! running ; then
+            echo "$NAME."
+        else
+            echo " ERROR."
+        fi
+	;;
+  #reload)
+	#
+	#	If the daemon can reload its config files on the fly
+	#	for example by sending it SIGHUP, do it here.
+	#
+	#	If the daemon responds to changes in its config file
+	#	directly anyway, make this a do-nothing entry.
+	#
+	# echo "Reloading $DESC configuration files."
+	# start-stop-daemon --stop --signal 1 --quiet --pidfile \
+	#	/var/run/$NAME.pid --exec $DAEMON
+  #;;
+  force-reload)
+	#
+	#	If the "reload" option is implemented, move the "force-reload"
+	#	option to the "reload" entry above. If not, "force-reload" is
+	#	just the same as "restart" except that it does nothing if the
+	#   daemon isn't already running.
+	# check wether $DAEMON is running. If so, restart
+	start-stop-daemon --stop --test --quiet --pidfile $PIDFILE \
+        --startas $DAEMON \
+	&& $0 restart \
+	|| exit 0
+	;;
   restart)
     echo -n "Restarting $DESC: "
     start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
-    [ -n "$DODTIME" ] && sleep $DODTIME
-    start-stop-daemon --start --quiet --pidfile \
-        $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
-    echo "$NAME."
-  ;;
+	[ -n "$DODTIME" ] && sleep $DODTIME
+	start-stop-daemon --start --quiet --pidfile $PIDFILE \
+		--startas $DAEMON -- $DAEMON_OPTS
+	echo "$NAME."
+	;;
   status)
-    echo -n "$DESC is "
+    echo -n "$NAME is "
     if running ;  then
         echo "running"
     else
         echo " not running."
         exit 1
     fi
-  ;;
+    ;;
   *)
-    N=/etc/init.d/$NAME
-    echo "Usage: $N {start|stop|restart|status|force-stop}" >&2
-    exit 1
-  ;;
+	N=/etc/init.d/$NAME
+	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
+	echo "Usage: $N {start|stop|restart|force-reload|status|force-stop}" >&2
+	exit 1
+	;;
 esac
 
 exit 0
