Update init.d script (Increase DODTIME to 8s)

diff --git a/templates/services/init.j2 b/templates/services/init.j2
--- a/templates/services/init.j2
+++ b/templates/services/init.j2
@@ -1,14 +1,14 @@
 #! /bin/sh
 #
-# skeleton  example file to build /etc/init.d/ scripts.
-#       This file should be used to construct scripts for /etc/init.d.
+# skeleton    example file to build /etc/init.d/ scripts.
+#        This file should be used to construct scripts for /etc/init.d.
 #
-#       Written by Miquel van Smoorenburg <miquels@cistron.nl>.
-#       Modified for Debian
-#       by Ian Murdock <imurdock@gnu.ai.mit.edu>.
+#        Written by Miquel van Smoorenburg <miquels@cistron.nl>.
+#        Modified for Debian
+#        by Ian Murdock <imurdock@gnu.ai.mit.edu>.
 #               Further changes by Javier Fernandez-Sanguino <jfs@debian.org>
 #
-# Version:  @(#)skeleton  1.9  26-Feb-2001  miquels@cistron.nl
+# Version:    @(#)skeleton  1.9  26-Feb-2001  miquels@cistron.nl
 #
 ### BEGIN INIT INFO
 # Provides:          supervisor
@@ -30,8 +30,9 @@ DESC=supervisor
 
 test -x $DAEMON || exit 0
 
+LOGDIR={{ elao_supervisor_log_dir }}
 PIDFILE=/var/run/$NAME.pid
-DODTIME=5                   # Time to wait for the server to die, in seconds
+DODTIME=8                   # Time to wait for the server to die, in seconds
                             # If this value is set too low you might not
                             # let some servers to die gracefully and
                             # 'restart' will not work
@@ -79,7 +80,7 @@ force_stop() {
             kill -9 $pid
             [ -n "$DODTIME" ] && sleep "$DODTIME"s
             if running ; then
-                echo "Cannot kill $DESC (pid=$pid)!"
+                echo "Cannot kill $NAME (pid=$pid)!"
                 exit 1
             fi
         fi
@@ -90,13 +91,9 @@ force_stop() {
 
 case "$1" in
   start)
-    if [ -e $PIDFILE ]; then
-        echo "$DESC already running with pid: `cat $PIDFILE`"
-        exit 0
-    fi
     echo -n "Starting $DESC: "
     start-stop-daemon --start --quiet --pidfile $PIDFILE \
-        --exec $DAEMON -- $DAEMON_OPTS
+        --startas $DAEMON -- $DAEMON_OPTS
     test -f $PIDFILE || sleep 1
         if running ; then
             echo "$NAME."
@@ -111,12 +108,18 @@ case "$1" in
     ;;
   force-stop)
     echo -n "Forcefully stopping $DESC: "
-    force_stop
-    if ! running ; then
-        echo "$NAME."
-    else
-        echo " ERROR."
-    fi
+        force_stop
+        if ! running ; then
+            echo "$NAME."
+        else
+            echo " ERROR."
+        fi
+    ;;
+  force-reload)
+    start-stop-daemon --stop --test --quiet --pidfile $PIDFILE \
+        --startas $DAEMON \
+    && $0 restart \
+    || exit 0
     ;;
   restart)
     echo -n "Restarting $DESC: "
@@ -143,3 +146,4 @@ case "$1" in
 esac
 
 exit 0
+
